### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by t0xic0der** [t0xic0der/sysmon#18]
In the spirit of getting more contributors to the project, the above document would be appreciated.

**Comment by erdinhrmwn** [comment]
I'll work this issue

**Comment by cybrpnkkrtos** [comment]
#21 Apologies had to make some modification in the image source tag now completed

**Comment by t0xic0der** [comment]
> I'll work this issue

@erdinhrmwn,

**Asking politely for an assignment would be appreciated.**

The maintainers of this repository spend countless hours into QAing the project and checking the stuff which can be added so the least, the contributors can do is to ask for issue assignment politely and not state that you are taking it right away.

For your reference @s-katte @VaibhavSaini19 @shivangswain

**Comment by t0xic0der** [comment]
Closed #18 via #20/#21.
