### ISSUE TITLE
Add CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by t0xic0der** [t0xic0der/sysmon#19]
In the spirit of getting more contributors to the project, the above document would be appreciated.

**Comment by cybrpnkkrtos** [comment]
I would like to help , would you like it in bulleted forms straight to point or as paras including some formal statements for contributors?

**Comment by cybrpnkkrtos** [comment]
#21 the PR for CODE_OF_CONDUCT.md was in the same PR as making Contributing.md , i was sceptical to create a new branch , if you wish to create a new branch i can make a new PR to that branch adding Code_of_conduct.md

**Comment by t0xic0der** [comment]
Cool. I am assigning this issue to you. Do make separate PRs per issue.

Feel free to leave a :star: at this repository, should you find it helpful.

**Comment by cybrpnkkrtos** [comment]
#22 done adding code_of_conduct.md as separate PR #22

**Comment by t0xic0der** [comment]
Closed #19 via #22.
