### ISSUE TITLE
Design a good looking icon for the project

### ISSUE THREAD

**Issue by t0xic0der** [t0xic0der/sysmon#32]
A lock won't work for long.

![image](https://user-images.githubusercontent.com/49605954/97656518-abcd4700-1a8d-11eb-80bc-06d3e4666ace.png)

**Comment by pk-95** [comment]
Hey, I'd like to work on this! 
What format would you require the icon in?

**Comment by t0xic0der** [comment]
I think @VaibhavSaini19 and @s-katte would be able to answer this in a much better way.

**Comment by VaibhavSaini19** [comment]
@pk-95 The icon needs to be in SVG format. Try to keep it simple so that when it is displayed at small sizes, it is still clearly visible. Also, make sure it has an aspect ratio of 1:1

**Comment by s-katte** [comment]
Adding to @VaibhavSaini19, try to keep the logo circular, that would be an easy option for 1:1 in my opinion. You are open for other options too.
